manage_worksheets/urls.py
from django.conf.urls import patterns, url

from manage_worksheets import views, ajax

urlpatterns = patterns('',
    # html pages
    url(r'^$', views.main, name='main'),
    url(r'^submit$', views.submit, name='submit'),
    url(r'^sso/submit/(?P<worksheet_id>.*)$', views.sso_submit, name='sso_submit'),
    url(r'^w/(?P<worksheet_pk>\d+)/login$', views.loggedin_details, name='loggedin_details'),
    url(r'^w/(?P<worksheet_pk>\d+)/delete$', views.delete, name='delete'),
    url(r'^w/(?P<worksheet_pk>\d+)/tags$', views.choose_tags, name='choose_tags'),
    url(r'^w/(?P<worksheet_pk>\d*)$', views.details, name='details'),

    # redirect
    url(r'^pokalid/(?P<worksheet_id>.*)$', views.redirect_from_pid),

    # ajax functions
    url(r'^tags$', ajax.tags, name='tags'),
    url(r'^worksheet_details/(?P<worksheet_pk>\d+)$', ajax.worksheet_details, name='worksheet_details'),
    url(r'^worksheet_list$', ajax.worksheet_list, name='worksheet_list'),
    url(r'^worksheets_for_tag/(?P<tag_id>\d+)', ajax.worksheets_for_tag, name='worksheets_for_tag'),
    url(r'^minus_tag/(?P<tag_id>\d+)', ajax.minus_tag, name='minus_tag'),
    url(r'^sso/move/(?P<from_id>\w+?)/(?P<to_id>\w+)', ajax.move, name='move'),
    url(r'^check/(?P<worksheet_id>\w+)$', ajax.check_wsid, name='check_wsid'),
)

poak/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'poak.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^poak/admin/', include(admin.site.urls)),
    url(r'^poak/u/', include('users.urls', namespace='users')),
    url(r'^poak/', include('manage_worksheets.urls', namespace='manage_worksheets')),
    url(r'^poak/blog/comments/', include('fluent_comments.urls')),
)

manage_worksheets/models.py
from django.db import models
from django.core.urlresolvers import reverse
from threadedcomments.models import ThreadedComment

class Tag(models.Model):
    name = models.CharField(max_length=50)
    def __unicode__(self):
        return self.name

class Worksheet(models.Model):
    worksheet_id = models.CharField(max_length=20)
    title = models.CharField(max_length=200)
    tags = models.ManyToManyField(Tag)
    pub_date = models.DateTimeField(auto_now_add=True)
    # TODO: remove "author"
    owner = models.CharField(max_length=20)
    author = models.CharField(max_length=200)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.title

    def data(self):
        """
        Encode data of Worksheet in a dictionary
        """
        dictionary = {
            'worksheet_id': self.worksheet_id,
            'title': self.title,
            'tags': [t.name for t in self.tags.all()],
            'pub_date': self.pub_date.isoformat(),
            'owner': self.owner,
            'score': (self.upvotes-self.downvotes),
            'comments':
            ThreadedComment.objects.filter(object_pk=self.pk).count(),
            'pk': self.pk,
        }
        return dictionary

    def add_tags(self, tags):
        for tag in tags:
            self.tags.add(tag)

    def get_absolute_url(self):
        return reverse('manage_worksheets:details',
                    args=[self.pk])

manage_worksheets/forms.py
from django import forms
from manage_worksheets.models import Tag

class SubmissionForm(forms.Form):
    url = forms.URLField(widget=forms.URLInput(
            attrs={'class': 'form-control'}),
            max_length=200,
            label="Adresse (URL)"
            )

    tags = forms.ModelMultipleChoiceField(
            widget=forms.CheckboxSelectMultiple(attrs={'class': ''}),
            queryset=Tag.objects.all(),
            label="Schlagworte",
            required=False           # choosing tags is not mandatory
            )

class ChooseTagsForm(forms.Form):
    tags = forms.ModelMultipleChoiceField(
            widget=forms.CheckboxSelectMultiple(attrs={'class': ''}),
            queryset=Tag.objects.all(),
            label="Schlagworte",
            required=False
            )
    def __init__(self, *args, **kwargs):
        worksheet = kwargs.pop('worksheet', None)
        #del kwargs['worksheet']
        super(ChooseTagsForm, self).__init__(*args, **kwargs)
        if worksheet:
            self.initial['tags'] = [t.pk for t in worksheet.tags.all()]

manage_worksheets/views.py
from django.shortcuts import render, get_object_or_404
from manage_worksheets.models import Tag, Worksheet
from manage_worksheets.forms import SubmissionForm, ChooseTagsForm
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from poak.settings import POKAL_URL
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied, SuspiciousOperation
import requests
from functions import get_POKAL_username


def main(request):
    return render(request, "manage_worksheets/index.html")

@login_required
def submit(request):
    """
    three possibilies:
    1. called with post data from a submission
    2. called with a get parameter with an ID
    3. called without any parameters
    """

    if request.method == 'POST':
        # form was submitted
        form = SubmissionForm(request.POST)
        if not form.is_valid():
            return render(request, "manage_worksheets/submit.html", {
                'form': SubmissionForm(),
                'error': True,
            })

        url = form.cleaned_data['url']
        tags = form.cleaned_data['tags']

        try:
            # process the submission
            w = _save_worksheet(request, url)
            w.tags = tags
            # if there was no error, everything is fine
            return HttpResponseRedirect(
                        reverse('manage_worksheets:details',
                        args=[w.pk]))
        except ValueError:
            # there was an error
            return render(request, "manage_worksheets/submit.html", {
                'tags': Tag.objects.all(),
                'form': SubmissionForm(),
                'error': True,
            })
    else: # no post data
        try:
            # see if there is get data
            worksheet_id = request.GET['id']
            form = SubmissionForm(initial={"url":POKAL_URL+"/"+worksheet_id})
        except KeyError:
            form = SubmissionForm()

        return render(request, "manage_worksheets/submit.html", {
            'error': False,
            'pokal_url': POKAL_URL,
            'form': form,
            })

def _save_worksheet(request, url, worksheet_id=None, user=None):
    """
    creates a new database entry for the given worksheet

    the URL is checked for being a valid POKAL-URL. But only if worksheet_id
    is not given.

    if no owner is given, set the currently logged-in user as the owner
    """
    if worksheet_id == None: # url has to be checked
        # the pattern is "base_url/worksheet_id/"
        if url[-1] == '/':
            url = url[:-1] # get rid of the last slash

        base_url, worksheet_id = url.rsplit('/', 1) # split in two parts

        # test if the base url ist correct
        if (base_url != POKAL_URL
            and base_url != POKAL_URL.replace("https://", "http://", 1)):
            raise ValueError

    if Worksheet.objects.filter(worksheet_id=worksheet_id).exists():
        # worksheet is already in database
        raise PermissionDenied

    # get data from POKAL
    r = requests.get(url+'/worksheet_properties')

    # if the following fails, it raises a ValueError
    worksheet_properties = r.json()

    try:
        title = worksheet_properties['name']
        owner = worksheet_properties['worksheet_that_was_published'][0]
    except KeyError:
        raise ValueError # to make handling easier, make everything ValueErrors

    if user == None:
        user = request.user.username

    if owner != user:
        raise PermissionDenied

    # make new entry in the database
    w = Worksheet(worksheet_id=worksheet_id,
            title=title, owner=owner, author="")
    w.save()
    return w

def details(request, worksheet_pk):
    worksheet = get_object_or_404(Worksheet, pk=worksheet_pk)
    return render(request, "manage_worksheets/details.html", {
        'worksheet': worksheet,
        'pokal_url': POKAL_URL,
        })

@login_required
def loggedin_details(request, worksheet_pk):
    return HttpResponseRedirect(
                reverse('manage_worksheets:details',
                args=[worksheet_pk]))

@login_required
def delete(request, worksheet_pk):
    worksheet = get_object_or_404(Worksheet, pk=worksheet_pk)

    # see if user is allowed to delete
    if worksheet.owner != request.user.username:
        raise PermissionDenied

    worksheet.delete()
    return render(request, "manage_worksheets/delete_success.html", {
        'worksheet_pk': worksheet_pk,
    })

def sso_submit(request, worksheet_id):
    """
    two possibilies:
    1. called with post data from a submission
    2. called with a get parameter with an ID
    """
    user = get_POKAL_username(request)
    if user == None or user == "guest":
        raise PermissionDenied

    try:
        # save worksheet to the database
        url = POKAL_URL+"/"+worksheet_id
        w = _save_worksheet(request, url, worksheet_id=worksheet_id, user=user)
    except ValueError:
        raise SuspiciousOperation

    return render(request, "manage_worksheets/sso_submit_success.html", {
        'worksheet': w,
    })

@login_required
def choose_tags(request, worksheet_pk):
    worksheet = get_object_or_404(Worksheet, pk=worksheet_pk)

    # see if user is allowed to do this
    if worksheet.owner != request.user.username:
        raise PermissionDenied

    if request.method == 'POST': # tag were chosen

        form = ChooseTagsForm(request.POST)
        if not form.is_valid():
            raise SuspiciousOperation

        # get data
        tags = form.cleaned_data['tags']

        # add the chosen tags to the worksheet in the database
        worksheet.tags = tags

        return HttpResponseRedirect(
                    reverse('manage_worksheets:details',
                    args=[worksheet_pk]))
    else:
        # get the tags that are currently associated with the worksheet
        tagids = [tag.pk for tag in worksheet.tags.all()]

        # render form with these initial values
        form = ChooseTagsForm(initial={'tags':tagids})
        return render(request, "manage_worksheets/choose_tags.html", {
            'form': form,
            'worksheet': worksheet,
        })

def redirect_from_pid(request, worksheet_id):
    worksheet = get_object_or_404(Worksheet, worksheet_id=worksheet_id)
    return HttpResponseRedirect(
            reverse('manage_worksheets:details',
            args=[worksheet.pk])
            )

manage_worksheets/templates/manage_worksheets/choose_tags.html
{% extends "base.html" %}

{% block main %}
    <h1></h1>
<div class="col-xs-12 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
	<div class="well well-sm text-center">
		<strong>Arbeitsblatt:</strong>
<a href="{% url 'manage_worksheets:details' worksheet.pk %}">
{{ worksheet.title }}</a>
	</div>
</div>
<form name="new_worksheet"
    action="{% url 'manage_worksheets:choose_tags' worksheet.pk %}" 
    method="post">
<div class="col-sm-12 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Wähle passende Schlagworte</h3>
		</div>
		<div class="panel-body">
			{% csrf_token %}
		{# Include the hidden fields #}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
		{# Include the visible fields #}
			<div id="tags" class="form-group">
				<label for="{{ form.tags.id_for_label }}" class="col-sm-6 col-md-4 control-label">{{ form.tags.label }}</label>
				<div class="col-sm-6 col-md-8">
					{{ form.tags.errors }}
                    <ul id="id_tags" class="list-group">
                        {% for tag in form.tags %}
                        <li class="list-group-item">
                        <label for="{{ tag.id_for_label }}">
                            {{ tag.tag }}
                            &nbsp;{{ tag.choice_label }}
                        </label>
                        </li>
                        {% endfor %}
                    </ul>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<div class="row">
				<div class="col-sm-6 col-md-4">
					<a class="btn btn-default" href="{% url 'manage_worksheets:main' %}">Zurück</a>
				</div>
				<div class="col-sm-6 col-md-8 text-right">
					<button type="submit" class="btn btn-primary">Abschicken</button>
				</div>
			</div>
		</div>
	</div>
</div>
</form>
{% endblock %}

manage_worksheets/templates/manage_worksheets/delete_success.html
{% extends "base.html" %}

{% block main %}
<div class="alert alert-success" role="alert">Das Arbeitsblatt mit der ID {{ worksheet_id }} wurde erfolgreich gelöscht.</div>
<a class="btn btn-default" href="{% url 'manage_worksheets:main' %}">Zurück zur Startseite</a>
{% endblock %}

manage_worksheets/templates/manage_worksheets/details.html
{% extends "base.html" %}
{% load threadedcomments_tags %}
{% load comments %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}fluent_comments/css/ajaxcomments.css" />
	<script type="text/javascript" src="{{ STATIC_URL }}fluent_comments/js/ajaxcomments.js"></script>
{% endblock %}

{% block main %}
<div id="worksheetdetails">
	<h2>
		<a href="{{ pokal_url }}/{{ worksheet.worksheet_id }}">{{ worksheet.title }}</a>
		{% if user.username == worksheet.owner %}
		<a class="btn btn-default"
        href="{% url 'manage_worksheets:choose_tags' worksheet.pk %}">
            Schlagworte ändern</a>
		<a class="btn btn-danger"
            href="{% url 'manage_worksheets:delete' worksheet.pk %}">
            Aus POAK entfernen</a>
		{% endif %}
	</h2>
	<div class="col-sm-12 col-md-6">
		<div id="tags">
			{% for tag in worksheet.tags.all %}
			<span class="label label-primary">{{ tag.name }}</span>
			{% endfor %}
		</div>
		<div>
			<dl class="dl-horizontal">
				<dt class="author">Autor</dt>
				<dd>{{ worksheet.owner }}</dd>
				<dt class="datetime">Hinzugefügt</dt>
				<dd>{{ worksheet.pub_date|date:"d.m.Y" }},{{ worksheet.pub_date|date:"H:i" }} Uhr</dd>
			</dl>
		</div>
		<div>
			<a class="btn btn-default" href="{% url 'manage_worksheets:main' %}">Zurück zur Startseite</a>
		</div>
	</div>
	
	<div class="col-sm-12 col-md-6">
		{% get_comment_count for worksheet as comment_count %}
		<h4 class="leading">Kommentare</h4>
		{% render_comment_list for worksheet %}
		{% if comment_count == 0 %}
		<div class="alert alert-info" role="alert">Noch keine Kommentare vorhanden.</div>
		{% endif %}
	
		{% if user.is_authenticated %}
		{% render_comment_form for worksheet %}
		{% else %}
		<div>
			<a class="btn btn-default" href="
                {% url 'manage_worksheets:loggedin_details' worksheet.pk %}">
                Anmelden</a> um zu kommentieren.
		</div>
	</div>
	{% endif %}
</div>
{% endblock %}

manage_worksheets/templates/manage_worksheets/index.html
{% extends "base.html" %}

{% block head %}
{% load static from staticfiles %}
<script type="text/javascript" src="{% static 'manage_worksheets/js/indexview.js' %}"></script>
{% endblock %}

{% block main %}
	<div class="col-xs-12">
		<div class="well well-sm text-center">
			<strong><abbr title="Physik Online Arbeitsblatt-Katalog">POAK</abbr></strong> ist unsere Plattform, um veröffentlichte POKAL-Arbeitsblätter leichter zugänglich und nach verschiedenen Schlagworten durchsuchbar zu machen.
		</div>
	</div>
	
	<div class="col-md-4 col-lg-3">
		<div id="tags" class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Schlagwörter <small>(Filter)</small></h3>
			</div>
			<!--<div class="panel-body"></div>-->
			<ul class="list-group">
				<li class="list-group-item"><label><input id="tagall" type="checkbox" checked /> Alle</label></li>
			</ul>
		</div>
	</div>

	<div class="col-md-8 col-lg-9">
		<div id="worksheets" class="panel panel-default">
			<div class="panel-heading">
				<a class="btn btn-primary btn-sm pull-right" href="{% url 'manage_worksheets:submit' %}" style="margin-top: -6px">Neues Arbeitsblatt einreichen</a>
				<h3 class="panel-title">Passende Arbeitsblätter</h3>
			</div>
			<!--<div class="panel-body"></div>-->
			<ul class="list-group">
			</ul>
		</div>
	</div>
{% endblock %}

manage_worksheets/templates/manage_worksheets/sso_submit_success.html
{% extends "base.html" %}

{% block main %}
<div class="alert alert-success" role="alert">Das Arbeitsblatt mit dem Titel
    "{{ worksheet.title }}" (ID:{{ worksheet.worksheet_id }}) wurde erfolgreich veröffentlicht.</div>
<a class="btn btn-default"
    href="{% url 'manage_worksheets:details' worksheet.pk %}">
    Details zum Arbeitsblatt.</a>
<a class="btn btn-default"
    href="{% url 'manage_worksheets:choose_tags' worksheet.pk %}">
    Dem Arbeitsblatt Schlagworte hinzufügen.</a>
<a class="btn btn-default" href="{% url 'manage_worksheets:main' %}">Zu POAK</a>
{% endblock %}

manage_worksheets/templates/manage_worksheets/submit.html
{% extends "base.html" %}

{% block navbar-left %}
<li><a href="{% url 'manage_worksheets:main' %}">Zurück zum Katalog</a></li>
{% endblock %}

{% block main %}

{% if error %}
<div class="alert alert-danger" role="alert">Ein Fehler ist aufgetreten!</div>
{% endif %}
<form name="new_worksheet" action="{% url 'manage_worksheets:submit' %}" method="post" class="form-horizontal" role="form">
<div class="col-sm-12 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Neues Arbeitsblatt einreichen</h3>
		</div>
		<div class="panel-body">
			{% csrf_token %}
		{# Include the hidden fields #}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
		{# Include the visible fields #}
			<div class="form-group">
				<label for="{{ form.url.id_for_label }}" class="col-sm-6 col-md-4 control-label">{{ form.url.label }}</label>
				<div class="col-sm-6 col-md-8">
					{{ form.url.errors }}
					{{ form.url }}
				</div>
			</div>
			<div id="tags" class="form-group">
				<label for="{{ form.tags.id_for_label }}" class="col-sm-6 col-md-4 control-label">{{ form.tags.label }}</label>
				<div class="col-sm-6 col-md-8">
					{{ form.tags.errors }}
					<ul id="id_tags" class="list-group">
                        {% for tag in form.tags %}
					    <li class="list-group-item">
                        <label for="{{ tag.id_for_label }}">
                            {{ tag.tag }}
                            &nbsp;{{ tag.choice_label }}
                        </label>
                        </li>
                        {% endfor %}
                    </ul>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<div class="row">
				<div class="col-sm-6 col-md-4">
					<a class="btn btn-default" href="{% url 'manage_worksheets:main' %}">Zurück</a>
				</div>
				<div class="col-sm-6 col-md-8 text-right">
					<button type="submit" class="btn btn-primary">Abschicken</button>
				</div>
			</div>
		</div>
	</div>
</div>
</form>
{% endblock %}