manage_worksheets/urls.py
from django.conf.urls import patterns, url

from manage_worksheets import views, ajax

urlpatterns = patterns('',
    # html pages
    url(r'^$', views.main, name='main'),
    url(r'^submit$', views.submit, name='submit'),
    url(r'^sso/submit/(?P<worksheet_id>.*)$', views.sso_submit, name='sso_submit'),
    url(r'^w/(?P<worksheet_pk>\d+)/login$', views.loggedin_details, name='loggedin_details'),
    url(r'^w/(?P<worksheet_pk>\d+)/delete$', views.delete, name='delete'),
    url(r'^w/(?P<worksheet_pk>\d+)/tags$', views.choose_tags, name='choose_tags'),
    url(r'^w/(?P<worksheet_pk>\d*)$', views.details, name='details'),

    # redirect
    url(r'^pokalid/(?P<worksheet_id>.*)$', views.redirect_from_pid),

    # ajax functions
    url(r'^tags$', ajax.tags, name='tags'),
    url(r'^worksheet_details/(?P<worksheet_pk>\d+)$', ajax.worksheet_details, name='worksheet_details'),
    url(r'^worksheet_list$', ajax.worksheet_list, name='worksheet_list'),
    url(r'^worksheets_for_tag/(?P<tag_id>\d+)', ajax.worksheets_for_tag, name='worksheets_for_tag'),
    url(r'^minus_tag/(?P<tag_id>\d+)', ajax.minus_tag, name='minus_tag'),
    url(r'^sso/move/(?P<from_id>\w+?)/(?P<to_id>\w+)', ajax.move, name='move'),
    url(r'^check/(?P<worksheet_id>\w+)$', ajax.check_wsid, name='check_wsid'),
)

poak/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'poak.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^poak/admin/', include(admin.site.urls)),
    url(r'^poak/u/', include('users.urls', namespace='users')),
    url(r'^poak/', include('manage_worksheets.urls', namespace='manage_worksheets')),
    url(r'^poak/blog/comments/', include('fluent_comments.urls')),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', name="my_login"),
    url(r'^account/$', views.account, name="account"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'registration/logout.html'}, name="my_logout")
    )

templates/base.html
<!DOCTYPE html>
<html lang="de">
<head>
    <title>{% block title %}Physik Online Arbeitsblatt-Katalog{% endblock %}</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "lib/bootstrap-3.2.0-dist/css/bootstrap.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="/data/bootstrap-3.2.0/css/bootstrap-theme.pokal2.css" />
    <link type="text/css" rel="stylesheet" href="{% static "manage_worksheets/css/main.css" %}" />
    <script type="text/javascript" src="{% static "lib/jquery-1.11.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "lib/bootstrap-3.2.0-dist/js/bootstrap.min.js" %}">
    </script>
    {% block head %}{% endblock %}
</head>

<body role="document">
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'manage_worksheets:main' %}">Physik Online Arbeitsblatt-Katalog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
		  {% block navbar-left %}
            <li><a href="/">Zurück zu Pokal</a></li>
		  {% endblock %}
          </ul>
		  <ul class="nav navbar-nav navbar-right">
			{% block navbar-right %}
			{% if user.is_authenticated %}
			<li><p class="navbar-text">Eingeloggt als <a class="navbar-link" href="{% url 'users:account' %}">{{ user.username }}</a></p></li>
			<li><a href="{% url 'users:my_logout' %}">Abmelden</a></li>
			{% else %}
			<li><a href="{% url 'users:my_login' %}">Anmelden</a></li>
			{% endif %}
			{% endblock %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
	
    <div id="main" class="container" role="main">
        {% block main %}{% endblock %}
    </div>
</body>
</html>